import { useCallback, useEffect, useMemo, useState } from 'react';
import { useAuth } from '@clerk/clerk-react';
import { markApplied } from '../api/client';
import type { EventCard, FilterOption, SwipeDirection, SwipedLists } from '../types';

const MOCK_CARDS: EventCard[] = [
  {
    id: '1',
    subject: 'AI/ML Workshop: Building Your First Neural Network',
    sender: 'Princeton AI Club',
    preview: 'Join us for a hands-on workshop where you\'ll build and train your first neural network from scratch. No prior ML experience required! We\'ll cover the fundamentals of deep learning and walk through a complete project.',
    type: 'event',
    eventType: 'workshop',
    atmosphere: 'skill-building',
    applyLink: 'https://forms.google.com/ai-workshop',
    eventDate: 'December 5',
    location: 'Friend Center 101',
    tags: ['AI', 'Workshop'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '2',
    subject: 'Startup Founders Panel: From Dorm Room to Series A',
    sender: 'Princeton Entrepreneurship Club',
    preview: 'Hear from 4 successful founders who started their companies while in college. Learn about fundraising, building a team, and balancing academics with your startup dreams.',
    type: 'event',
    eventType: 'speaker',
    atmosphere: 'skill-building',
    applyLink: 'https://forms.google.com/founders-panel',
    eventDate: 'December 8',
    location: 'McCosh 50',
    tags: ['Entrepreneurship', 'Speaker'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '3',
    subject: 'Princeton Robotics Club - Join Us!',
    sender: 'Robotics Club',
    preview: 'We build autonomous robots that compete in national competitions. From mechanical design to software, there\'s a role for everyone. Weekly meetings and hands-on projects.',
    type: 'club',
    clubType: 'stem',
    atmosphere: 'tight-knit',
    applyLink: 'https://forms.google.com/robotics',
    tags: ['Robotics', 'STEM'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '4',
    subject: 'HackPrinceton 2024 - Registration Open!',
    sender: 'HackPrinceton Team',
    preview: '36-hour hackathon with $10,000 in prizes! Build something amazing, meet recruiters from top tech companies, and enjoy free food and swag. Beginners welcome!',
    type: 'event',
    eventType: 'competition',
    atmosphere: 'high-energy',
    applyLink: 'https://forms.google.com/hackprinceton',
    eventDate: 'January 15-17',
    location: 'Friend Center',
    tags: ['Hackathon', 'Competition'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '5',
    subject: 'Investment Club General Meeting',
    sender: 'Princeton Investment Club',
    preview: 'Weekly meeting to discuss market trends, pitch stock ideas, and learn about different investment strategies. Great for anyone interested in finance or trading.',
    type: 'event',
    eventType: 'meeting',
    atmosphere: 'skill-building',
    applyLink: 'https://forms.google.com/investment-club',
    eventDate: 'Every Thursday',
    location: 'Bendheim Center',
    tags: ['Finance', 'Meeting'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '6',
    subject: 'A Cappella Jam Session & Open Rehearsal',
    sender: 'Princeton Tigertones',
    preview: 'Come sing with us! Open rehearsal for anyone interested in a cappella. No audition required for this session - just bring your voice and good vibes.',
    type: 'event',
    eventType: 'practice',
    atmosphere: 'just-for-fun',
    applyLink: 'https://forms.google.com/tigertones',
    eventDate: 'December 3',
    location: 'Woolworth Music Building',
    tags: ['Music', 'A Cappella'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '7',
    subject: 'Consulting Club Case Competition',
    sender: 'Princeton Consulting Club',
    preview: 'Test your problem-solving skills in our annual case competition. Work in teams to crack real business cases. Prizes include interviews with top consulting firms!',
    type: 'event',
    eventType: 'competition',
    atmosphere: 'high-energy',
    applyLink: 'https://forms.google.com/case-comp',
    eventDate: 'December 12',
    location: 'Robertson Hall',
    tags: ['Consulting', 'Competition'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '8',
    subject: 'Princeton Debate Panel - Join Our Community',
    sender: 'Princeton Debate Panel',
    preview: 'Competitive debate team that travels to tournaments nationwide. We practice argumentation, public speaking, and critical thinking. All experience levels welcome.',
    type: 'club',
    clubType: 'academic',
    atmosphere: 'tight-knit',
    applyLink: 'https://forms.google.com/debate',
    tags: ['Debate', 'Academic'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '9',
    subject: 'End of Semester Social Mixer',
    sender: 'Princeton CS Club',
    preview: 'Celebrate the end of finals with fellow CS students! Food, drinks, games, and networking. A great chance to meet people across all years and connect with TAs.',
    type: 'event',
    eventType: 'social',
    atmosphere: 'large-social',
    applyLink: 'https://forms.google.com/cs-mixer',
    eventDate: 'December 18',
    location: 'CS Building Atrium',
    tags: ['Social', 'Networking'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '10',
    subject: 'Princeton Asian American Students Association',
    sender: 'AASA',
    preview: 'Cultural organization celebrating Asian American heritage through events, discussions, and community service. Join our family and connect with your culture!',
    type: 'club',
    clubType: 'cultural',
    atmosphere: 'tight-knit',
    applyLink: 'https://forms.google.com/aasa',
    tags: ['Cultural', 'Community'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '11',
    subject: 'Design Sprint Workshop: UX Fundamentals',
    sender: 'Princeton Design Club',
    preview: 'Learn the basics of user experience design in this intensive workshop. We\'ll cover user research, wireframing, and prototyping using industry-standard tools.',
    type: 'event',
    eventType: 'workshop',
    atmosphere: 'skill-building',
    applyLink: 'https://forms.google.com/ux-workshop',
    eventDate: 'December 7',
    location: 'Lewis Library',
    tags: ['Design', 'UX'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '12',
    subject: 'Club Soccer Tryouts',
    sender: 'Princeton Club Soccer',
    preview: 'Competitive club soccer team looking for new players! We practice 3x/week and compete against other Ivy League schools. All skill levels encouraged to try out.',
    type: 'club',
    clubType: 'sports',
    atmosphere: 'high-energy',
    applyLink: 'https://forms.google.com/club-soccer',
    tags: ['Sports', 'Soccer'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '13',
    subject: 'Princeton Volunteer Council - Spring Break Trip',
    sender: 'Community Action',
    preview: 'Join us for an alternative spring break trip focused on education equity. Work with underserved schools and make a real impact. Applications due January 10.',
    type: 'club',
    clubType: 'volunteer',
    atmosphere: 'tight-knit',
    applyLink: 'https://forms.google.com/spring-break',
    tags: ['Volunteer', 'Service'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '14',
    subject: 'Theatre Intime Winter Production Auditions',
    sender: 'Theatre Intime',
    preview: 'Auditions for our winter mainstage production! We\'re looking for actors, singers, and dancers. No prepared monologue needed - come ready to have fun.',
    type: 'event',
    eventType: 'practice',
    atmosphere: 'just-for-fun',
    applyLink: 'https://forms.google.com/theatre-auditions',
    eventDate: 'December 4-5',
    location: 'Hamilton Murray Theater',
    tags: ['Theatre', 'Arts'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '15',
    subject: 'Princeton Pre-Med Society Info Session',
    sender: 'Pre-Med Society',
    preview: 'Learn about the medical school application process, MCAT prep, and clinical opportunities. Q&A with current medical students and recent alumni.',
    type: 'event',
    eventType: 'meeting',
    atmosphere: 'skill-building',
    applyLink: 'https://forms.google.com/premed-info',
    eventDate: 'December 9',
    location: 'Frist 302',
    tags: ['Pre-Med', 'Career'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '16',
    subject: 'Daily Princetonian - Writers Wanted!',
    sender: 'The Daily Princetonian',
    preview: 'Join Princeton\'s independent student newspaper! We\'re looking for news reporters, opinion writers, sports journalists, and multimedia creators.',
    type: 'club',
    clubType: 'media',
    atmosphere: 'skill-building',
    applyLink: 'https://forms.google.com/prince-writers',
    tags: ['Journalism', 'Writing'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '17',
    subject: 'Game Night & Chill',
    sender: 'Princeton Gaming Club',
    preview: 'Weekly casual gaming sessions - board games, card games, and video games. No commitment required, just drop by when you want to destress and have fun!',
    type: 'event',
    eventType: 'social',
    atmosphere: 'chill',
    applyLink: 'https://forms.google.com/game-night',
    eventDate: 'Every Friday',
    location: 'Frist Game Room',
    tags: ['Gaming', 'Social'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '18',
    subject: 'Princeton E-Club: Building Your First MVP',
    sender: 'Entrepreneurship Club',
    preview: 'Workshop on how to build a minimum viable product for your startup idea. Learn about rapid prototyping, user testing, and iterating on feedback.',
    type: 'event',
    eventType: 'workshop',
    atmosphere: 'skill-building',
    applyLink: 'https://forms.google.com/mvp-workshop',
    eventDate: 'December 10',
    location: 'Prospect House',
    tags: ['Startup', 'Workshop'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '19',
    subject: 'Outdoor Action Leaders - Spring Training',
    sender: 'Outdoor Action',
    preview: 'Become a leader for Princeton\'s premier outdoor program! Lead trips for incoming freshmen and develop wilderness skills. Training starts in February.',
    type: 'club',
    clubType: 'sports',
    atmosphere: 'tight-knit',
    applyLink: 'https://forms.google.com/oa-leaders',
    tags: ['Outdoors', 'Leadership'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '20',
    subject: 'VC Speaker: How We Evaluate Startups',
    sender: 'Princeton Venture Capital Club',
    preview: 'Guest speaker from Andreessen Horowitz discusses how VCs evaluate early-stage startups. Learn what investors look for and how to pitch your company.',
    type: 'event',
    eventType: 'speaker',
    atmosphere: 'skill-building',
    applyLink: 'https://forms.google.com/vc-speaker',
    eventDate: 'December 11',
    location: 'Julis Romo Rabinowitz Building',
    tags: ['VC', 'Speaker'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '21',
    subject: 'Quantum Computing Research Talk',
    sender: 'Princeton Quantum Initiative',
    preview: 'Faculty research presentation on recent breakthroughs in quantum error correction. Great opportunity to learn about cutting-edge research and potential thesis topics.',
    type: 'event',
    eventType: 'speaker',
    atmosphere: 'skill-building',
    applyLink: 'https://forms.google.com/quantum-talk',
    eventDate: 'December 13',
    location: 'Jadwin Hall A10',
    tags: ['Quantum', 'Research'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '22',
    subject: 'Princeton Cycling Club',
    sender: 'Cycling Club',
    preview: 'Road cycling group for all levels. Weekly group rides, bike maintenance workshops, and occasional races. Bikes available for those who need them.',
    type: 'club',
    clubType: 'sports',
    atmosphere: 'chill',
    applyLink: 'https://forms.google.com/cycling',
    tags: ['Cycling', 'Fitness'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '23',
    subject: 'Photography Workshop: Night Photography',
    sender: 'Princeton Photo Club',
    preview: 'Learn long exposure techniques, light painting, and astrophotography basics. Bring your camera (DSLRs or mirrorless recommended). Tripods provided.',
    type: 'event',
    eventType: 'workshop',
    atmosphere: 'skill-building',
    applyLink: 'https://forms.google.com/night-photo',
    eventDate: 'December 6',
    location: 'Campus Green',
    tags: ['Photography', 'Workshop'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '24',
    subject: 'Mock Trial Team Tryouts',
    sender: 'Princeton Mock Trial',
    preview: 'Compete in collegiate mock trial tournaments! Learn courtroom procedures, develop public speaking skills, and argue cases. No legal experience needed.',
    type: 'club',
    clubType: 'academic',
    atmosphere: 'high-energy',
    applyLink: 'https://forms.google.com/mock-trial',
    tags: ['Mock Trial', 'Law'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '25',
    subject: 'Data Science Career Panel',
    sender: 'Princeton Data Science Club',
    preview: 'Alumni panel featuring data scientists from Google, Meta, and startups. Learn about career paths, skills to develop, and how to break into the field.',
    type: 'event',
    eventType: 'speaker',
    atmosphere: 'skill-building',
    applyLink: 'https://forms.google.com/ds-panel',
    eventDate: 'December 14',
    location: 'Friend Center 006',
    tags: ['Data Science', 'Career'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '26',
    subject: 'Princeton Ballroom Dance Club',
    sender: 'Ballroom Dance',
    preview: 'Learn waltz, tango, salsa, and swing! Weekly lessons for beginners and practice sessions for experienced dancers. No partner needed.',
    type: 'club',
    clubType: 'arts',
    atmosphere: 'just-for-fun',
    applyLink: 'https://forms.google.com/ballroom',
    tags: ['Dance', 'Social'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '27',
    subject: 'Sustainability Hackathon',
    sender: 'Princeton Environmental Club',
    preview: '24-hour hackathon focused on climate tech solutions. Build apps, hardware prototypes, or policy proposals. Mentors from environmental organizations.',
    type: 'event',
    eventType: 'competition',
    atmosphere: 'high-energy',
    applyLink: 'https://forms.google.com/eco-hack',
    eventDate: 'January 20-21',
    location: 'Andlinger Center',
    tags: ['Sustainability', 'Hackathon'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '28',
    subject: 'Model United Nations Conference',
    sender: 'Princeton MUN',
    preview: 'Host high school delegates at our annual conference. Serve as a chair, crisis director, or staff member. Great leadership experience!',
    type: 'event',
    eventType: 'competition',
    atmosphere: 'high-energy',
    applyLink: 'https://forms.google.com/mun-conf',
    eventDate: 'February 10-12',
    location: 'Various Campus Venues',
    tags: ['MUN', 'Conference'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '29',
    subject: 'Chess Club Weekly Tournament',
    sender: 'Princeton Chess Club',
    preview: 'Casual weekly tournaments with Swiss pairings. All skill levels from beginners to masters. Free pizza and great atmosphere!',
    type: 'event',
    eventType: 'competition',
    atmosphere: 'chill',
    applyLink: 'https://forms.google.com/chess-tourney',
    eventDate: 'Every Wednesday',
    location: 'Frist 200',
    tags: ['Chess', 'Competition'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '30',
    subject: 'Princeton Latinx Students Association',
    sender: 'LSA',
    preview: 'Cultural org celebrating Latinx heritage through events, mentorship, and advocacy. Join for study breaks, cultural nights, and community.',
    type: 'club',
    clubType: 'cultural',
    atmosphere: 'tight-knit',
    applyLink: 'https://forms.google.com/lsa',
    tags: ['Cultural', 'Latinx'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '31',
    subject: 'Machine Learning Paper Reading Group',
    sender: 'Princeton ML Club',
    preview: 'Weekly sessions dissecting influential ML papers. Great for research prep and keeping up with the field. All experience levels welcome.',
    type: 'event',
    eventType: 'meeting',
    atmosphere: 'skill-building',
    applyLink: 'https://forms.google.com/ml-papers',
    eventDate: 'Every Tuesday',
    location: 'CS Building 105',
    tags: ['ML', 'Research'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '32',
    subject: 'Princeton Running Club',
    sender: 'Running Club',
    preview: 'Daily group runs at various paces. From casual joggers to marathon trainers. Join for accountability, social runs, and occasional races.',
    type: 'club',
    clubType: 'sports',
    atmosphere: 'chill',
    applyLink: 'https://forms.google.com/running',
    tags: ['Running', 'Fitness'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '33',
    subject: 'Creative Writing Workshop Series',
    sender: 'Princeton Creative Writing Club',
    preview: 'Four-week workshop series covering fiction, poetry, and creative nonfiction. Share your work, get feedback, and improve your craft.',
    type: 'event',
    eventType: 'workshop',
    atmosphere: 'tight-knit',
    applyLink: 'https://forms.google.com/cw-workshop',
    eventDate: 'Starts January 8',
    location: 'Whitman College',
    tags: ['Writing', 'Creative'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '34',
    subject: 'Women in STEM Networking Dinner',
    sender: 'Princeton SWE',
    preview: 'Annual networking dinner with women engineers from industry. Build connections, get career advice, and enjoy a great meal.',
    type: 'event',
    eventType: 'social',
    atmosphere: 'large-social',
    applyLink: 'https://forms.google.com/swe-dinner',
    eventDate: 'December 15',
    location: 'Prospect House',
    tags: ['SWE', 'Networking'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '35',
    subject: 'Princeton Anime Club',
    sender: 'Anime Club',
    preview: 'Weekly anime screenings, manga discussions, and cosplay meetups. Casual and welcoming community for all anime fans.',
    type: 'club',
    clubType: 'social',
    atmosphere: 'chill',
    applyLink: 'https://forms.google.com/anime',
    tags: ['Anime', 'Social'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '36',
    subject: 'Blockchain Technology Workshop',
    sender: 'Princeton Blockchain Club',
    preview: 'Hands-on workshop building a simple blockchain from scratch. Learn about consensus mechanisms, smart contracts, and Web3 development.',
    type: 'event',
    eventType: 'workshop',
    atmosphere: 'skill-building',
    applyLink: 'https://forms.google.com/blockchain-ws',
    eventDate: 'December 16',
    location: 'Friend Center 008',
    tags: ['Blockchain', 'Workshop'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '37',
    subject: 'Princeton Ultimate Frisbee',
    sender: 'Ultimate Club',
    preview: 'Competitive and recreational ultimate frisbee. Practice 4x/week with tournaments throughout the semester. Spirit of the game!',
    type: 'club',
    clubType: 'sports',
    atmosphere: 'high-energy',
    applyLink: 'https://forms.google.com/ultimate',
    tags: ['Ultimate', 'Sports'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '38',
    subject: 'Public Policy Research Symposium',
    sender: 'Princeton Policy Club',
    preview: 'Student presentations on policy research projects. Topics range from healthcare to climate to education. Great prep for junior papers.',
    type: 'event',
    eventType: 'speaker',
    atmosphere: 'skill-building',
    applyLink: 'https://forms.google.com/policy-symp',
    eventDate: 'December 17',
    location: 'Robertson Hall 100',
    tags: ['Policy', 'Research'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '39',
    subject: 'Princeton Black Student Union',
    sender: 'BSU',
    preview: 'Community organization for Black students and allies. Events, discussions, mentorship, and advocacy. Come find your home.',
    type: 'club',
    clubType: 'cultural',
    atmosphere: 'tight-knit',
    applyLink: 'https://forms.google.com/bsu',
    tags: ['Cultural', 'Community'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '40',
    subject: 'Cooking Club: Holiday Baking Edition',
    sender: 'Princeton Cooking Club',
    preview: 'Learn to make holiday cookies, pies, and treats from around the world. All ingredients provided. Take home your creations!',
    type: 'event',
    eventType: 'workshop',
    atmosphere: 'just-for-fun',
    applyLink: 'https://forms.google.com/holiday-baking',
    eventDate: 'December 19',
    location: 'Forbes College Kitchen',
    tags: ['Cooking', 'Social'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '41',
    subject: 'Princeton Film Society Screening',
    sender: 'Film Society',
    preview: 'Weekly classic and contemporary film screenings followed by discussion. This week: Parasite (2019). Free admission and popcorn!',
    type: 'event',
    eventType: 'social',
    atmosphere: 'chill',
    applyLink: 'https://forms.google.com/film-screening',
    eventDate: 'Every Saturday',
    location: 'McCarter Theatre',
    tags: ['Film', 'Arts'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '42',
    subject: 'Princeton Climbing Club',
    sender: 'Climbing Club',
    preview: 'Indoor and outdoor climbing for all levels. Free gear rentals, weekly gym sessions, and weekend trips to real rock. No experience needed!',
    type: 'club',
    clubType: 'sports',
    atmosphere: 'tight-knit',
    applyLink: 'https://forms.google.com/climbing',
    tags: ['Climbing', 'Outdoors'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '43',
    subject: 'Economics Research Assistant Info Session',
    sender: 'Princeton Economics Department',
    preview: 'Learn about RA opportunities with faculty. Get research experience, potential thesis topics, and recommendation letters. Sophomores and juniors welcome.',
    type: 'event',
    eventType: 'meeting',
    atmosphere: 'skill-building',
    applyLink: 'https://forms.google.com/econ-ra',
    eventDate: 'December 20',
    location: 'Julis Romo Rabinowitz Building',
    tags: ['Economics', 'Research'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '44',
    subject: 'Princeton Acapellago',
    sender: 'Acapellago',
    preview: 'All-gender a cappella group performing contemporary pop and indie music. Auditions in January - follow us on Instagram for details!',
    type: 'club',
    clubType: 'arts',
    atmosphere: 'tight-knit',
    applyLink: 'https://forms.google.com/acapellago',
    tags: ['A Cappella', 'Music'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '45',
    subject: 'Healthcare Technology Innovation Challenge',
    sender: 'Princeton HealthTech',
    preview: 'Design solutions for real healthcare problems. Work with clinicians and patients to build prototypes. Top teams present to healthcare VCs.',
    type: 'event',
    eventType: 'competition',
    atmosphere: 'high-energy',
    applyLink: 'https://forms.google.com/healthtech',
    eventDate: 'January 25-27',
    location: 'Engineering Quad',
    tags: ['HealthTech', 'Competition'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '46',
    subject: 'Princeton Badminton Club',
    sender: 'Badminton Club',
    preview: 'Recreational and competitive badminton. Weekly practice sessions with coaching. Equipment provided for beginners.',
    type: 'club',
    clubType: 'sports',
    atmosphere: 'chill',
    applyLink: 'https://forms.google.com/badminton',
    tags: ['Badminton', 'Sports'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '47',
    subject: 'Tiger Magazine Open Pitch Meeting',
    sender: 'Tiger Magazine',
    preview: 'Pitch your article ideas for our spring issue! We cover campus culture, student life, and longform journalism. All writers welcome.',
    type: 'event',
    eventType: 'meeting',
    atmosphere: 'skill-building',
    applyLink: 'https://forms.google.com/tiger-mag',
    eventDate: 'January 5',
    location: 'Frist 309',
    tags: ['Journalism', 'Writing'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '48',
    subject: 'Princeton Meditation & Mindfulness',
    sender: 'Mindfulness Club',
    preview: 'Weekly guided meditation sessions for stress relief and mental wellness. No experience needed. All practices and traditions welcome.',
    type: 'club',
    clubType: 'social',
    atmosphere: 'chill',
    applyLink: 'https://forms.google.com/meditation',
    tags: ['Wellness', 'Mindfulness'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '49',
    subject: 'Product Management Workshop',
    sender: 'Princeton Product Club',
    preview: 'Learn PM fundamentals: user research, roadmapping, and cross-functional collaboration. Case studies from successful PMs at tech companies.',
    type: 'event',
    eventType: 'workshop',
    atmosphere: 'skill-building',
    applyLink: 'https://forms.google.com/pm-workshop',
    eventDate: 'December 21',
    location: 'Friend Center 101',
    tags: ['Product', 'Career'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '50',
    subject: 'Princeton Vietnamese Students Association',
    sender: 'VSA',
    preview: 'Cultural org celebrating Vietnamese heritage. Monthly events, Tet celebration, and community service. Connect with your culture!',
    type: 'club',
    clubType: 'cultural',
    atmosphere: 'tight-knit',
    applyLink: 'https://forms.google.com/vsa',
    tags: ['Cultural', 'Vietnamese'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '51',
    subject: 'Improv Comedy Workshop',
    sender: 'Princeton Quipfire!',
    preview: 'Learn the basics of improvisational comedy! Games, exercises, and lots of laughs. Perfect for beginners. No audition required.',
    type: 'event',
    eventType: 'workshop',
    atmosphere: 'just-for-fun',
    applyLink: 'https://forms.google.com/improv-workshop',
    eventDate: 'January 7',
    location: 'Murray Theater',
    tags: ['Improv', 'Comedy'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '52',
    subject: 'Princeton Rocketry Club',
    sender: 'Rocketry Club',
    preview: 'Design and launch high-powered rockets! Compete in national competitions. Workshops on propulsion, avionics, and recovery systems.',
    type: 'club',
    clubType: 'stem',
    atmosphere: 'tight-knit',
    applyLink: 'https://forms.google.com/rocketry',
    tags: ['Rocketry', 'Engineering'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '53',
    subject: 'Alumni Mentor Matching Event',
    sender: 'Princeton Career Services',
    preview: 'Speed-networking event to connect with alumni mentors in your field of interest. Finance, tech, consulting, healthcare, and more.',
    type: 'event',
    eventType: 'social',
    atmosphere: 'large-social',
    applyLink: 'https://forms.google.com/mentor-match',
    eventDate: 'January 12',
    location: 'Nassau Hall',
    tags: ['Career', 'Networking'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '54',
    subject: 'Princeton Table Tennis Club',
    sender: 'Table Tennis',
    preview: 'Casual and competitive table tennis. Weekly practice, lessons for beginners, and inter-club tournaments. Tables always available!',
    type: 'club',
    clubType: 'sports',
    atmosphere: 'chill',
    applyLink: 'https://forms.google.com/table-tennis',
    tags: ['Table Tennis', 'Sports'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '55',
    subject: 'Neuroscience Research Opportunities',
    sender: 'Princeton Neuroscience Institute',
    preview: 'Info session on undergraduate research in neuroscience labs. Learn about ongoing projects, how to apply, and what to expect.',
    type: 'event',
    eventType: 'meeting',
    atmosphere: 'skill-building',
    applyLink: 'https://forms.google.com/neuro-research',
    eventDate: 'January 8',
    location: 'PNI A32',
    tags: ['Neuroscience', 'Research'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '56',
    subject: 'Princeton Fashion Collective',
    sender: 'Fashion Collective',
    preview: 'Design, style, and produce fashion shows. Workshops on design, photography, and event production. Creative community for fashion enthusiasts.',
    type: 'club',
    clubType: 'arts',
    atmosphere: 'tight-knit',
    applyLink: 'https://forms.google.com/fashion',
    tags: ['Fashion', 'Design'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '57',
    subject: 'Cybersecurity CTF Competition',
    sender: 'Princeton Security Club',
    preview: 'Capture-the-flag competition for all skill levels. Learn web security, cryptography, and reverse engineering. Prizes for top teams!',
    type: 'event',
    eventType: 'competition',
    atmosphere: 'high-energy',
    applyLink: 'https://forms.google.com/ctf',
    eventDate: 'January 18',
    location: 'Friend Center',
    tags: ['Security', 'CTF'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '58',
    subject: 'Princeton Ski & Snowboard Club',
    sender: 'Ski Club',
    preview: 'Weekend trips to mountains in Vermont and Pennsylvania. Group rates, bus transportation, and lessons available. All levels welcome!',
    type: 'club',
    clubType: 'sports',
    atmosphere: 'large-social',
    applyLink: 'https://forms.google.com/ski-club',
    tags: ['Skiing', 'Snowboarding'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '59',
    subject: 'Philosophy Discussion Circle',
    sender: 'Princeton Philosophy Club',
    preview: 'Weekly discussions on ethics, metaphysics, and epistemology. Read short texts and debate big questions. No philosophy background needed.',
    type: 'event',
    eventType: 'meeting',
    atmosphere: 'chill',
    applyLink: 'https://forms.google.com/philosophy',
    eventDate: 'Every Monday',
    location: '1879 Hall',
    tags: ['Philosophy', 'Discussion'],
    receivedAt: new Date().toISOString(),
  },
  {
    id: '60',
    subject: 'Princeton South Asian Students',
    sender: 'Desi Students Association',
    preview: 'Celebrating South Asian culture through Garba, Diwali, and more. Social events, cultural programming, and tight-knit community.',
    type: 'club',
    clubType: 'cultural',
    atmosphere: 'large-social',
    applyLink: 'https://forms.google.com/dsa',
    tags: ['Cultural', 'South Asian'],
    receivedAt: new Date().toISOString(),
  },
];

export const useSwipeDeck = () => {
  const { getToken } = useAuth();
  const [cards, setCards] = useState<EventCard[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | undefined>();
  const [filter, setFilter] = useState<FilterOption>('all');
  const [pendingCard, setPendingCard] = useState<EventCard | null>(null);
  const [isConfirming, setIsConfirming] = useState(false);
  const [appliedIds, setAppliedIds] = useState<Set<string>>(new Set());
  const [swipedLists, setSwipedLists] = useState<SwipedLists>({
    interested: [],
    notInterested: [],
    reviewLater: [],
  });

  const loadCards = useCallback(async (selectedFilter: FilterOption = filter) => {
    setLoading(true);
    setError(undefined);
    try {
      // Use mock data for demo
      let data = [...MOCK_CARDS];
      if (selectedFilter === 'event') {
        data = data.filter(card => card.type === 'event');
      } else if (selectedFilter === 'club') {
        data = data.filter(card => card.type === 'club');
      }
      setCards(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load cards');
    } finally {
      setLoading(false);
    }
  }, [filter]);

  useEffect(() => {
    loadCards(filter);
  }, [filter, loadCards]);

  const swipe = useCallback((direction: SwipeDirection, card: EventCard) => {
    setCards((prev) => prev.filter((item) => item.id !== card.id));
    if (direction === 'right') {
      setSwipedLists((prev) => ({
        ...prev,
        interested: [...prev.interested, card],
      }));
    } else if (direction === 'left') {
      setSwipedLists((prev) => ({
        ...prev,
        notInterested: [...prev.notInterested, card],
      }));
    } else if (direction === 'up') {
      setSwipedLists((prev) => ({
        ...prev,
        reviewLater: [...prev.reviewLater, card],
      }));
    }
  }, []);

  const dismissPending = useCallback(() => setPendingCard(null), []);

  const confirmApplied = useCallback(async () => {
    if (!pendingCard) return;
    try {
      setIsConfirming(true);
      // Get Clerk session token - backend will extract Google OAuth token from Clerk
      const token = await getToken();
      await markApplied(pendingCard.id, token);
      setAppliedIds((prev) => new Set(prev).add(pendingCard.id));
      setPendingCard(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not add to calendar');
    } finally {
      setIsConfirming(false);
    }
  }, [pendingCard, getToken]);

  const hasCards = useMemo(() => cards.length > 0, [cards]);

  const clearSwipedList = useCallback((listKey: 'interested' | 'notInterested' | 'reviewLater') => {
    setSwipedLists((prev) => ({
      ...prev,
      [listKey]: [],
    }));
  }, []);

  const removeFromSwipedList = useCallback((listKey: 'interested' | 'notInterested' | 'reviewLater', cardId: string) => {
    setSwipedLists((prev) => ({
      ...prev,
      [listKey]: prev[listKey].filter((card) => card.id !== cardId),
    }));
  }, []);

  return {
    cards,
    loading,
    error,
    filter,
    setFilter,
    swipe,
    reload: () => loadCards(filter),
    pendingCard,
    confirmApplied,
    dismissPending,
    appliedIds,
    isConfirming,
    hasCards,
    swipedLists,
    clearSwipedList,
    removeFromSwipedList,
  };
};
